export const FBX_MAPPING_MODE_NONE = 0;
export const FBX_MAPPING_MODE_CONTROL_POINT = 1;
export const FBX_MAPPING_MODE_POLYGON_VERTEX = 2;
export const FBX_MAPPING_MODE_POLYGON = 3;
export const FBX_MAPPING_MODE_EDGE = 4;
export const FBX_MAPPING_MODE_ALL_SAME = 5;
