 export const FBX_TC_LEGACY_MILLISECOND = 46186158n;
 export const FBX_TC_LEGACY_SECOND = FBX_TC_LEGACY_MILLISECOND * 1000n;

export const FBX_TC_MILLISECOND = 141120n;
export const FBX_TC_SECOND = FBX_TC_MILLISECOND * 1000n;
export const FBX_TC_MINUTE = FBX_TC_SECOND * 60n;
export const FBX_TC_HOUR = FBX_TC_MINUTE * 60n;
export const FBX_TC_DAY = FBX_TC_MINUTE * 24n;
